import yaml from 'js-yaml'
import { createAdminClient } from '@/lib/supabase/admin'
import type { TriggerSource, ActiveOrderForProxy } from '@/types/domain'
import type { ProxyConfig, PoolGroup } from './types'
import { pushYamlToProxy } from './push'

const FALLBACK_POOL_URL = process.env.FALLBACK_POOL_URL ?? 'pool.swisshash.com:3333'
const FALLBACK_WORKER = 'swisshash.fallback'

async function loadActiveOrders(): Promise<ActiveOrderForProxy[]> {
  const supabase = createAdminClient()

  const { data, error } = await supabase
    .from('orders')
    .select(`
      id,
      hashrate_th,
      pool_config_id,
      customer_pool_configs (
        pool_url,
        pool_port,
        worker_name,
        password,
        tls
      ),
      profiles!orders_customer_id_fkey (
        email
      )
    `)
    .eq('status', 'active')
    .gt('expires_at', new Date().toISOString())

  if (error) throw new Error(`Failed to load active orders: ${error.message}`)

  return (data ?? []).map(row => ({
    id: row.id,
    hashrate_th: row.hashrate_th,
    customer_email: (row.profiles as { email: string } | null)?.email ?? 'unknown',
    pool_config: row.customer_pool_configs
      ? {
          pool_url: (row.customer_pool_configs as unknown as { pool_url: string }).pool_url,
          pool_port: (row.customer_pool_configs as unknown as { pool_port: number }).pool_port,
          worker_name: (row.customer_pool_configs as unknown as { worker_name: string }).worker_name,
          password: (row.customer_pool_configs as unknown as { password: string }).password,
          tls: (row.customer_pool_configs as unknown as { tls: boolean }).tls,
        }
      : null,
  }))
}

function buildPoolGroups(orders: ActiveOrderForProxy[]): { groups: PoolGroup[]; totalTH: number } {
  if (orders.length === 0) {
    return {
      groups: [
        {
          group: 'swisshash_fallback',
          weight: 1.0,
          pools: [{ url: FALLBACK_POOL_URL, user: FALLBACK_WORKER, pass: 'x', tls: false }],
        },
      ],
      totalTH: 0,
    }
  }

  const totalTH = orders.reduce((sum, o) => sum + o.hashrate_th, 0)

  // Build raw float weights
  const rawWeights = orders.map(o => o.hashrate_th / totalTH)

  // Round to 4 decimal places
  const rounded = rawWeights.map(w => Math.round(w * 10000) / 10000)

  // Rounding correction: apply diff to largest entry
  const sum = rounded.reduce((a, b) => a + b, 0)
  const diff = Math.round((1.0 - sum) * 10000) / 10000
  const maxIdx = rounded.indexOf(Math.max(...rounded))
  rounded[maxIdx] = Math.round((rounded[maxIdx] + diff) * 10000) / 10000

  const groups: PoolGroup[] = orders.map((order, i) => {
    const pc = order.pool_config
    const poolUrl = pc ? `${pc.pool_url}:${pc.pool_port}` : FALLBACK_POOL_URL
    const worker = pc ? pc.worker_name : FALLBACK_WORKER
    const pass = pc ? pc.password : 'x'
    const tls = pc ? pc.tls : false

    return {
      group: `customer_${order.id.substring(0, 8)}`,
      weight: rounded[i],
      pools: [{ url: poolUrl, user: worker, pass, tls }],
    }
  })

  return { groups, totalTH }
}

function buildProxyConfig(groups: PoolGroup[]): ProxyConfig {
  return {
    log_level: 'info',
    api_port: 5010,
    log_dir: './configs/log',
    telemetry: null,
    upstream_tcp_settings: {
      keep_alive: {
        idle_time: { secs: 15, nanos: 0 },
        interval: { secs: 5, nanos: 0 },
        retries: 3,
      },
      user_timeout: '29s',
    },
    ports: [
      {
        bind_port: 3333,
        name: 'swisshash',
        active: true,
        submission_rate: 0.2,
        aggregation: 255,
        mining_algorithm: 'sha256d',
        pool_groups: groups,
      },
    ],
  }
}

async function getNextVersion(): Promise<number> {
  const supabase = createAdminClient()
  const { data } = await supabase
    .from('proxy_config_versions')
    .select('version')
    .order('version', { ascending: false })
    .limit(1)
    .single()

  return (data?.version ?? 0) + 1
}

export interface GenerateResult {
  version: number
  yaml: string
  total_hashrate_th: number
  active_order_count: number
  generated_at: string
  trigger_source: TriggerSource
}

export async function generateAndSaveProxyConfig(
  triggerSource: TriggerSource,
  triggerOrderId?: string,
  generatedBy?: string
): Promise<GenerateResult> {
  const orders = await loadActiveOrders()
  const { groups, totalTH } = buildPoolGroups(orders)
  const config = buildProxyConfig(groups)

  const version = await getNextVersion()
  const generatedAt = new Date().toISOString()

  const headerComment =
    `# Generated by SwissHash @ ${generatedAt}\n` +
    `# Version: ${version} | Active Orders: ${orders.length} | Total TH: ${totalTH}\n`

  const yamlContent = headerComment + yaml.dump(config, {
    indent: 2,
    lineWidth: -1,
    quotingType: '"',
  })

  const supabase = createAdminClient()
  const { error } = await supabase.from('proxy_config_versions').insert({
    version,
    yaml_content: yamlContent,
    total_hashrate_th: totalTH,
    active_order_count: orders.length,
    trigger_source: orders.length === 0 ? 'empty_fallback' : triggerSource,
    trigger_order_id: triggerOrderId ?? null,
    generated_by: generatedBy ?? null,
  })

  if (error) throw new Error(`Failed to save proxy config: ${error.message}`)

  // Push to VPS agent (no-op if PROXY_AGENT_URL not configured)
  try {
    await pushYamlToProxy(yamlContent)
  } catch (pushErr) {
    console.error('[proxy/generator] Failed to push config to VPS agent:', pushErr)
    // Don't throw — config is saved in DB, push failure is non-fatal
  }

  return {
    version,
    yaml: yamlContent,
    total_hashrate_th: totalTH,
    active_order_count: orders.length,
    generated_at: generatedAt,
    trigger_source: orders.length === 0 ? 'empty_fallback' : triggerSource,
  }
}
